apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-subscription
  namespace: olm
spec:
  channel: preview
  name: prometheus
  source: my-catalogsource
  sourceNamespace: olm
  installPlanApproval: Automatic
